---
title: Sur la route de l'IndieWeb
timezone: UTC
collections:
  notes:
    title: Notes
    output: true
    permalink: "/notes/:title.html"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
header-img: img/caterpillar.jpg
email: christophe.ducamp@gmail.com
description: Explorations Jekyll IndieWeb
baseurl: 
url: http://christopheducamp.com
twitter_username: xtof_fr
github_username: christopheducamp
facebook_username: christophe.ducamp
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts: 
css_class: highlight
permalink: "/:year/:month/:day/:title/"
paginate: 15
exclude:
- less
- node_modules
- Gruntfile.js
- package.json
- README.md
jekyll-mentions: https://twitter.com
twitter_format: "@title xtof.me@url @tags"
twitter_url_length: 22
twitter_max_length: 140
blog_title: sur la route indieweb...
blog_description: Premiers pas de non développeur sur le statique avec github et jekyll.
  Apprentissage en cours.
